### ISSUE TITLE
Intercept-builds fails for multithreaded buil

### ISSUE THREAD

**Issue by BonaBeavis** [rizsotto/scan-build#109]
When building [Godot](http://docs.godotengine.org/en/latest/development/compiling/compiling_for_x11.html).

`intercept-build scons -j 4 platform=x11 use_llvm=yes` fails randomly with
```
Traceback (most recent call last):
  File "/home/beavis/.local/bin/intercept-build", line 11, in <module>
    sys.exit(intercept_build())
  File "/home/beavis/.local/lib/python3.6/site-packages/libscanbuild/__init__.py", line 126, in wrapper
    return function()
  File "/home/beavis/.local/lib/python3.6/site-packages/libscanbuild/intercept.py", line 55, in intercept_build
    exit_code, current = capture(args)
  File "/home/beavis/.local/lib/python3.6/site-packages/libscanbuild/intercept.py", line 84, in capture
    return exit_code, iter(set(current))
  File "/home/beavis/.local/lib/python3.6/site-packages/libscanbuild/intercept.py", line 98, in compilations
    for call in exec_calls:
  File "/home/beavis/.local/lib/python3.6/site-packages/libscanbuild/intercept.py", line 81, in <genexpr>
    calls = (parse_exec_trace(file) for file in exec_trace_files(tmp_dir))
  File "/home/beavis/.local/lib/python3.6/site-packages/libscanbuild/intercept.py", line 226, in parse_exec_trace
    entry = json.load(handler)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 36 (char 35)
```
but `intercept-build scons -j 1 platform=x11 use_llvm=yes` works.

**Comment by lucmann** [comment]
> [rizsotto/Bear#209](https://github.com/rizsotto/Bear/issues/209)

Hi, 

this issue is still right here (I tested on 2.0.20 release). BTW, this project has not been maintained any more? @rizsotto

**Comment by rizsotto** [comment]
@lucmann it's hard to answer, I got no reply to my questions... it would be a minimal thing to know: what tool and what version of it we are talking? I am happy to help, but things like: "it fails on my machine" is difficult to address from my end, because all I can reply: "it works on my machine". :smile: 

The `scan-build` tool is still here. Not totally abandoned. (Will archive the repo, and will put a message about it into the README file.) The tool provides two things: run the static analyzer, and generates compilation database.

- Running the static analyzer, I think `clang-check` does a better job. Use that if you can.
- To generate compilation database, use Bear which also a better tool for it. (Bear does not cover M$ Windows, so that's the only reason why this project is not yet killed.)
