### ISSUE TITLE
analyze-build fail with pool.imap_unordered

### ISSUE THREAD

**Issue by jedichen121** [rizsotto/scan-build#117]
I was trying to use scan-build to analyze a compilation commands database. I generated the json file following this [guide](https://gist.github.com/bsilver8192/0115ee5d040bb601e3b7). However, the command `analyze-build --cdb compile_commands.json` failed with the following output: 
```
analyze-build: Removing directory '/tmp/scan-build-2019-09-10-22-22-48-613760-B5hcc6' because it contains no report.
Traceback (most recent call last):
  File "/usr/local/bin/analyze-build", line 11, in <module>
    sys.exit(analyze_build())
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/__init__.py", line 129, in wrapper
    return function()
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/analyze.py", line 85, in analyze_build
    run_analyzer_parallel(compilations, args)
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/analyze.py", line 181, in run_analyzer_parallel
    for current in pool.imap_unordered(run, parameters):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
ValueError: Expecting property name: line 5 column 7 (char 1025)
```
I'm using Ubuntu 16.04 with python 2.7. I also tried it again on an aarch64 with Ubuntu 18.04 and python 3.6. The result is similar: 
```
analyze-build: Removing directory '/tmp/scan-build-2019-09-10-22-22-20-177346-7xpb6j44' because it contains no report.
Traceback (most recent call last):
  File "/usr/local/bin/analyze-build", line 10, in <module>
    sys.exit(analyze_build())
  File "/usr/local/lib/python3.6/dist-packages/libscanbuild/__init__.py", line 129, in wrapper
    return function()
  File "/usr/local/lib/python3.6/dist-packages/libscanbuild/analyze.py", line 85, in analyze_build
    run_analyzer_parallel(compilations, args)
  File "/usr/local/lib/python3.6/dist-packages/libscanbuild/analyze.py", line 181, in run_analyzer_parallel
    for current in pool.imap_unordered(run, parameters):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 7 (char 1025)
```
Any help would be appreciated. Thank you.

**Comment by jedichen121** [comment]
I tried using a database generated by this [tool](https://github.com/grailbio/bazel-compilation-database) and this time it reports different errors. 
```
analyze-build: analysis failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/analyze.py", line 403, in run_analyzer
    cwd)
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/clang.py", line 46, in get_arguments
    output = run_command(cmd, cwd=cwd)
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/__init__.py", line 81, in run_command
    raise ex
CalledProcessError: Command '['clang', '-###', '--analyze', '-Xclang', '-analyzer-output=html', '-x', 'c++', '-U_FORTIFY_SOURCE', '-fstack-protector', '-Wno-free-nonheap-object', '-fno-omit-frame-pointer', '-std=c++0x', '-fno-canonical-system-headers', '-Wno-builtin-macro-redefined', '-D__DATE__=redacted', '-D__TIMESTAMP__=redacted', '-D__TIME__=redacted', '-iquote', '.', '-iquote', 'bazel-out/k8-fastbuild/bin', '-iquote', 'external/bazel_tools', '-iquote', 'bazel-out/k8-fastbuild/bin/external/bazel_tools', u'/home/jiyangchen/.cache/bazel/_bazel_jiyangchen/3f7a264a28e299764f33b15a9c73d122/execroot/__main__/main/hello-world.cc', '-o', '/home/jiyangchen/bazel_examples/cpp-tutorial/stage1/bazel-compilation-database-0.3.5/clang-analysis/scan-build-2019-09-11-11-31-13-064029-JXCNZD']' returned non-zero exit status 1
analyze-build: failed to report failure
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/analyze.py", line 360, in report_failure
    opts['flags'] + [opts['source'], '-o', name], cwd)
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/clang.py", line 46, in get_arguments
    output = run_command(cmd, cwd=cwd)
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/__init__.py", line 81, in run_command
    raise ex
CalledProcessError: Command '['clang', '-###', '-fsyntax-only', '-E', '-x', 'c++', '-U_FORTIFY_SOURCE', '-fstack-protector', '-Wno-free-nonheap-object', '-fno-omit-frame-pointer', '-std=c++0x', '-fno-canonical-system-headers', '-Wno-builtin-macro-redefined', '-D__DATE__=redacted', '-D__TIMESTAMP__=redacted', '-D__TIME__=redacted', '-iquote', '.', '-iquote', 'bazel-out/k8-fastbuild/bin', '-iquote', 'external/bazel_tools', '-iquote', 'bazel-out/k8-fastbuild/bin/external/bazel_tools', u'/home/jiyangchen/.cache/bazel/_bazel_jiyangchen/3f7a264a28e299764f33b15a9c73d122/execroot/__main__/main/hello-world.cc', '-o', '/home/jiyangchen/bazel_examples/cpp-tutorial/stage1/bazel-compilation-database-0.3.5/clang-analysis/scan-build-2019-09-11-11-31-13-064029-JXCNZD/failures/clang_other_error_LXDTK6.ii']' returned non-zero exit status 1
analyze-build: Run 'scan-view /home/jiyangchen/bazel_examples/cpp-tutorial/stage1/bazel-compilation-database-0.3.5/clang-analysis/scan-build-2019-09-11-11-31-13-064029-JXCNZD' to examine bug reports.
```
Are there any requirements on the compilation database itself? Thank you.

**Comment by rizsotto** [comment]
Hey @jedichen121 , thanks for the report.

Are you using bazel? This case it will be hard to help, mainly because

1. I have little experience with bazel. :)
2. Bazel compiles each file in a `chroot` like environment to avoid picking up the wrong header file, or linking against the wrong library (if you have multiple versions of the same on your computer).
3. The second might implies that the JSON compilation database has relative paths to the modules you are compiling. This case if you feed that with a tool like `scan-build` might not find the files.

Can you validate that the JSON compilation database is actually a good one? You can try that out with `clang-format` or `clang-tidy`. If those tools are also failing, then `scan-build` will too. If the tools are going well with it, then it's a bug on `scan-build`.

**Comment by jedichen121** [comment]
Hi @rizsotto , thank you for the reply. 

There doesn't seem to be any plug-in from bazel for clang right now and we have to abandon using scan-build to analyze our project. 

However, I tried `pvs-studio` and it actually worked with the compilation database from bazel. Just FYI.

**Comment by rizsotto** [comment]
@jedichen121 closing this ticket now. Will create a more generic one for `bazel`. Thanks for your feedbacks. (The PVS-Studio thing is noted, will try to look at their solution.)
