### ISSUE TITLE
Can't handle CC with arguments

### ISSUE THREAD

**Issue by AlefCS** [rizsotto/scan-build#133]
If the CC/CXX environment variable has not only the compiler but also some arguments (as it could happen for an [Yocto Environment Setup Script](https://docs.yoctoproject.org/2.3.3/sdk-manual/sdk-manual.html#sdk-running-the-extensible-sdk-environment-setup-script)) the `intercept-build` will fail.

Main reason is that `libear` do a call to `subprocess.check_call(cmd, *args, **kwargs)` with the first element of `cmd` being not only the compiler, but also some arguments (e.g.: `cmd == 'gcc -D_FORTIFY_SOURCE=2'`) and `subprocess.check_call()` can't deal with this, it will raise an exception saying that no such file was found. Each one with the flags should be a different element of `cmd` list.

This whole thing will result to an `LD_PRELOAD` of `NoneType` resulting on `intercept-build` to fail with an exception.

That's the traceback I get from `intercept-build`:
```
Traceback (most recent call last):
  File "/usr/local/bin/intercept-build", line 8, in <module>
    sys.exit(intercept_build())
  File "/usr/local/lib/python3.8/dist-packages/libscanbuild/__init__.py", line 129, in wrapper
    return function()
  File "/usr/local/lib/python3.8/dist-packages/libscanbuild/intercept.py", line 55, in intercept_build
    exit_code, current = capture(args)
  File "/usr/local/lib/python3.8/dist-packages/libscanbuild/intercept.py", line 79, in capture
    exit_code = run_build(args.build, env=environment)
  File "/usr/local/lib/python3.8/dist-packages/libscanbuild/__init__.py", line 52, in run_build
    exit_code = subprocess.call(command, *args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1626, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
  File "/usr/lib/python3.8/os.py", line 806, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by rizsotto** [comment]
Yes, this use case is not supported. I would recommend to use `CFLAGS` environment variable to pass compiler arguments to your build. (Build systems are usually support that.)

**Comment by AlefCS** [comment]
Saw in issue #96 that `intercept-build` would get rid of this project and we should use [Bear](https://github.com/rizsotto/Bear) instead. Tried it and it worked, so I'm closing this issue.
